name: Deploy FastAPI to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      - name: Copy files to VM
        run: |
          gcloud compute scp --recurse ./* \
            ${{ secrets.GCP_INSTANCE_NAME }}:/home/kaziuddin1509011/fastapi-app \
            --zone ${{ secrets.GCP_ZONE }}

      - name: Install dependencies and restart FastAPI service
        run: |
          gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} --zone ${{ secrets.GCP_ZONE }} --command="
            cd /home/kaziuddin1509011/fastapi-app &&
            python3 -m venv venv &&
            source venv/bin/activate &&
            pip install -r requirements.txt &&
            sudo systemctl restart fastapi
          "
